#!/bin/bash

# install .bashrc
if [ -f ~/.bashrc ]; then
    echo 'Skipping ~/.bashrc ...'
else
    if [ x"$OS" != x'Windows_NT' ]; then
        ln -s ~/.files/bashrc ~/.bashrc
    else
        echo 'source ~/.files/bashrc' > ~/.bashrc
    fi
fi

# install .profile
if [ -f ~/.profile ]; then
    echo 'Skipping ~/.profile ...'
else
    if [ x"$OS" != x'Windows_NT' ]; then
        ln -s ~/.files/profile ~/.profile
    else
        echo 'source ~/.files/profile' > ~/.profile
    fi
fi

# install .lesskey
if [ -f ~/.lesskey ]; then
    echo 'Skipping ~/.lesskey ...'
else
    if [ x"$OS" != x'Windows_NT' ]; then
        ln -s ~/.files/lesskey ~/.lesskey
    fi

    # compile .lesskey to get .less
    if [ x"$OS" != x'Windows_NT' ]; then
        lesskey
    else
        lesskey -o ~/.less -- ./lesskey
    fi
fi

# install .inputrc
if [ -f ~/.inputrc ]; then
    echo 'Skipping ~/.inputrc ...'
else
    if [ x"$OS" != x'Windows_NT' ]; then
        ln -s ~/.files/inputrc ~/.inputrc
    else
        echo '$include ~/.files/inputrc' > ~/.inputrc
    fi
fi

# install .tmux.conf
if [ -f ~/.tmux.conf ]; then
    echo 'Skipping ~/.tmux.conf ...'
else
    if [ x"$OS" != x'Windows_NT' ]; then
        ln -s ~/.files/tmux.conf ~/.tmux.conf
    else
        echo 'source-file ~/.files/tmux.conf' > ~/.tmux.conf
    fi
fi
