#!/bin/bash

# install .bashrc
if [ x"$OS" != x'Windows_NT' ]; then
    ln -s ~/.files/bashrc ~/.bashrc
else
    echo 'source ~/.files/bashrc' >| ~/.bashrc
fi

# install .profile
if [ x"$OS" != x'Windows_NT' ]; then
    ln -s ~/.files/profile ~/.profile
else
    echo 'source ~/.files/profile' >| ~/.profile
fi

# install .lesskey
if [ x"$OS" != x'Windows_NT' ]; then
    ln -s ~/.files/lesskey ~/.lesskey
fi

# compile .lesskey to get .less
if [ x"$OS" != x'Windows_NT' ]; then
    lesskey
else
    lesskey -o ~/.less -- ./lesskey
fi
